version: "3.9"
services:
  server:
    build: ./src/backend
    ports:
      - 80:5000
    volumes:
      - ./:/app/src/backend
    environment:
      FLASK_ENV: development
  web:
    build: ./
    ports:
      - 3000:3000
    volumes:
      - ./:/app/src
    depends_on:
      - server
